name: Build EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller selenium requests webdriver-manager

    - name: Download ChromeDriver
      run: |
        $latestVersion = (Invoke-RestMethod -Uri "https://chromedriver.storage.googleapis.com/LATEST_RELEASE").Trim()
        $chromeDriverUrl = "https://chromedriver.storage.googleapis.com/$latestVersion/chromedriver_win32.zip"
        Invoke-WebRequest -Uri $chromeDriverUrl -OutFile "chromedriver.zip"
        Expand-Archive "chromedriver.zip" -DestinationPath "."
        if (Test-Path "chromedriver.exe") { Write-Host "ChromeDriver downloaded successfully" } else { Write-Error "ChromeDriver not found" }

    - name: Build EXE
      run: |
        pyinstaller --onefile --add-data "chromedriver.exe;." --name review_photo review_photo.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: review_photo_exe
        path: dist/review_photo.exe 